networks:
  internal:
    driver: bridge

volumes:
  media_volume:
  static_volume:
  sqlite_volume:

services:
  backend:
    image: sashapenkin12/backend:latest
    mem_limit: 1g
    cpus: 0.5

    volumes:
      - media_volume:/app/photos
      - static_volume:/app/static
      - sqlite_volume:/app/db
    expose:
      - 8000
    networks:
      - internal
    restart: unless-stopped
    env_file: /etc/photoeasy/.env

  nginx:
    image: nginx:latest
    mem_limit: 512M
    cpus: 0.2

    networks:
      - internal
    ports:
      - "80:80"
#      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#      - /etc/letsencrypt:/etc/letsencrypt:ro
      - media_volume:/app/photos
      - static_volume:/app/static
    depends_on:
      - backend
    restart: unless-stopped