name: Deploy and Build to VPS

on:
  push:
    branches: [main]
    paths:
      - 'deploy/prod/**'
      - 'entrypoint.sh'


jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Copy required files
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: deploy/prod/
          target: ~/app/
          strip_components: 2

      - name: VPS Deploy
        uses: appleboy/ssh-action@v1.2.0
        timeout-minutes: 30
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/app

            # Пуллим Docker image и запускаем контейнеры
            docker compose pull
            docker compose up -d