name: Deploy to VPS

on:
  push:
    branches:
      - main


jobs:
#  build-and-push:
#    name: Build Docker Image
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Checkout project
#        uses: actions/checkout@v4
#
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v3
#
#      - name: Log in to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_PASSWORD }}
#
#      - name: Build and push image
#        uses: docker/build-push-action@v5
#        with:
#          context: .
#          file: ./Dockerfile
#          push: true
#          tags: ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
#    needs: build-and-push
    steps:
      - name: Debug files
        run: |
          echo "ROOT:"
          ls -R .
          echo "Check specific file:"
          ls -l deploy/prod/ || echo "Directory deploy/prod/ NOT FOUND"
      - name: Copy required files
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: deploy/prod/docker-compose.yaml
          target: ~/app/

      - name: VPS Deploy
        uses: appleboy/ssh-action@v1.2.0
        timeout-minutes: 30
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd ~/app

            # Пуллим Docker image и запускаем контейнеры
            docker compose pull
            docker compose up -d